apiVersion: v1
kind: Service
metadata:
  name: flask-image-gallery
spec:
  selector:
    app: flask-image-gallery
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-image-gallery
spec:
  selector:
    matchLabels:
      app: flask-image-gallery
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-image-gallery
    spec:
      containers:
      - name: vigorous-moser
        image: rat_ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000  