apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: browser
      port: 35585 
      targetPort: 35585
      protocol: TCP
  selector:
    app: minio
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-07-29T19-40-48Z
          args:
          - server
          - /data
          ports:
            - name: minio
              containerPort: 9090
              hostPort: 9090
              protocol: TCP
          volumeMounts:
            - name: s3-pv-storage
              mountPath: /data
          env:
          - name: MINIO_ACCESS_KEY
            value: "minio"
          - name: MINIO_SECRET_KEY
            value: "minio123"
      volumes:
        - name: s3-pv-storage
          persistentVolumeClaim:
            claimName: s3-pvc